### PR TITLE
Added dengun

### PR DESCRIPTION
**Pull request by amandoabreu**
A primeira Algarvia :)

### CODE REVIEW

**Comment by marmelo** [comment]
Hi @amandoabreu, can you please shorten the description?
Companies from Algarve are very welcome!

Thanks!

**Comment by marmelo** [comment]
Hi @amandoabreu, company categories have been added.
Can you please resolve conflicts and pick one?

Thanks!

**Comment by vpereira01** [comment]
ping @amandoabreu

**Comment by marmelo** [comment]
Pull request #68 has been approved.

**Pull request closed without merging**
