### PR TITLE
Change JUMO location to Remote

### PR DESCRIPTION
**Pull request by matosf**

### CODE REVIEW

**Comment by pedrorijo91** [comment]
looking at the careers page I could not see any indication of remote openings (https://www.jumo.world/careers/open-positions/). What's the source for this change?

**Comment by matosf** [comment]
You can see in that that page that all Engineering related positions (which are, atm,  the only ones we hire for in Portugal) are available in any of our Tech Hubs (i.e. Cape Town, Nairobi and Porto). 
We are now a remote-first company and also closed our Porto office, that is the reason of this change. 
The source is me, the [VP of Engineering](https://www.linkedin.com/in/fabiomatos/) of this company. 😉

**Review by pedrorijo91 — APPROVED** [review]

**Comment by pedrorijo91** [comment]
oh, that's a good source @matosf 😄  thanks for explaining. 

I think it can be confusing having location = Porto in the job opening when it's remote (Lisbon, Algarve, etc folks may not apply), but that's a company decision, not ours for sure :)

**Comment by matosf** [comment]
that is a good point. will ask to change the location to country, instead of city, on those jobs ads.

**Review by afonsojramos — APPROVED** [review]

**Pull request merged**
