### PR TITLE
Add PropTech section and Casafari company

### PR DESCRIPTION
**Pull request by dmytrostriletskyi**

### CODE REVIEW

**Comment by dmytrostriletskyi** [comment]
@marmelo, or anybody else, could you please clarify why my build is failed? I cannot catch which of the rules I didn't follow.

**Comment by vpereira01** [comment]
The pipeline is checking for dead links @dmytrostriletskyi which you can see on the lowest [Details link](https://travis-ci.org/marmelo/tech-companies-in-portugal/builds/660723357?utm_source=github_status&utm_medium=notification)

image

Since it's not a link that you added you can ignore it. Many corporations sites break from time to time.

----------------

On another note, PropTech seems to be Property Technology? 

I think it's not a well know term, do you think a more known naming can be used like Real Estate or  Property Technology?

**Comment by afonsojramos** [comment]
The build is failing due to some unrelated link issues, however, I have some questions over the creation of a new category. 

Do you think you can fit it within Specialized Consulting?

**Comment by dmytrostriletskyi** [comment]
Hi, all!

@vpereira01, `Property Technology` works for us, thank you.
@afonsojramos, `Specialized Consulting` doesn't fit us, sorry.

**Comment by marmelo** [comment]
Hi @dmytrostriletskyi, sorry for the delay.

I agree with @afonsojramos that usually I don't like to create new categories if only a single company fits.
The usual policy is to classify the company as "Enterprise Software" and then create a new category when other similar companies are added.
Or else we will end up having lots of categories with one or two companies.

I am performing this change and then merging.
Hope you agree. If not, lets discuss this further and then make changes.

Thanks.

**Comment by marmelo** [comment]
Thanks @dmytrostriletskyi, @vpereira01 and @afonsojramos!

**Pull request merged**
