### PR TITLE
Adds Vizzuality to the list

### PR DESCRIPTION
**Pull request by simaob**

### CODE REVIEW

**Comment by marmelo** [comment]
Hi @simaob,

I can find very little info about your Porto's office.
Can you please confirm that it has technology positions, either existing or available?

Thanks.

**Comment by simaob** [comment]
Hi,
We normally don't constrain our hirings to specific locations. You can see the currently open positions here: https://vizzuality.bamboohr.com/jobs/ . You can see that all our vacancies are for either Madrid, Porto, Cambridge or remote. And we currently have one open Software Engineer vacancy. And we just hired a new developer to work remotely from Braga.

Currently we have 5 people working from our Porto office, four developers and one Project Manager, plus the new developer who will work form Braga..

What other information would you be keen on?

We also were on Visão last year! http://visao.sapo.pt/verde/2018-01-18-Vai-instalar-se-no-Porto-empresa-de-mapas-que-trabalha-com-a-NASA-e-Di-Caprio =)

And you can find here our blog post about opening the Porto office: https://blog.vizzuality.com/post/170420818186/hello-porto 

Happy to provide more information as needed! =)

**Comment by simaob** [comment]
Apologies for the delay in getting back to you, I missed the notification!

**Comment by marmelo** [comment]
Thanks for the info @simaob!

Two more requests.
Can you please shorten the description to fit in a single line?
Also, there is something wrong with the careers :rocket: link.

Thanks.

**Comment by simaob** [comment]
Sorry for the typo on the emoji. Fixed now! Reduced the sentence as well. =)

**Comment by marmelo** [comment]
Thanks @simaob! :star:

**Pull request merged**
