### PR TITLE
Add Hitachi Vantara

### PR DESCRIPTION
**Pull request by nantunes**
Not sure if the Taguspark office location should be listed as `Taguspark`, `Porto Salvo` or `Oeiras`...

### CODE REVIEW

**Comment by marmelo** [comment]
Hi @nantunes, can you please shorten the description to fit in a single line? Thanks!

**Comment by marmelo** [comment]
Hi @nantunes, company categories have been added.
Can you please resolve conflicts and pick one?

Thanks!

**Comment by nantunes** [comment]
Done. Also moved Unit4 so it is ordered alphabetically.

Probably a squash merge will be cleaner.

**Comment by marmelo** [comment]
Thanks @nantunes! :star:

**Pull request merged**
