### PR TITLE
Added Pixelmatters

### PR DESCRIPTION
**Pull request by rgllm**

### CODE REVIEW

**Comment by marmelo** [comment]
Hi @rgllm,

My browser is throwing an `ERR_SSL_PROTOCOL_ERROR`  error with https://pixelmatters.com.
Downgrading to HTTP work OK, but is not cool.

Can you please check?

Thanks!

**Comment by rgllm** [comment]
@marmelo new site with https in the oven.

**Comment by marmelo** [comment]
Hi @rgllm, we can always go ahead with HTTP links and then update when available.
What do you think?

**Comment by rgllm** [comment]
@marmelo done 👍

**Comment by marmelo** [comment]
Thanks @rgllm!

**Pull request merged**
