### PR TITLE
Added iLoF and renamed Medical category

### PR DESCRIPTION
**Pull request by afonsojramos**
By the addition of iLoF, it came to mind that Medical should be renamed to BioTech.

What do you think?

### CODE REVIEW

**Comment by marmelo** [comment]
Hi @afonsojramos, I have two issues with this pull request.

First, what kind of company is iLoF?
Does it have employees with a computer science background? At least I did not find any in their site and Linkedin.
I realize that this is a list of "tech" companies, which could include Biotechnology... but that was not my intention.

I also do not agree with renaming the category.

What do you think?

**Comment by afonsojramos** [comment]
Hey @marmelo!

They are within the Med Tech actually, so my change was kind of wrongfully made.
Regarding the employees with computer science background, yes, they do, and from what I hear, they are recruiting.

**Comment by afonsojramos** [comment]
I'm getting a 404 on https://www.cgi.com/portugal/pt-pt/portugal/careers

**Comment by marmelo** [comment]
Thanks @afonsojramos! :star2:

**Pull request merged**
