### PR TITLE
Add Critical Manufacturing and Armis

### PR DESCRIPTION
**Pull request by rjcarneiro**
Hey 👋 

Two more companies here!

Great project, btw 👍

### CODE REVIEW

**Comment by rjcarneiro** [comment]
@marmelo Armis doesn't provide SSL web site

**Comment by marmelo** [comment]
Hi @rjcarneiro, can you please sort alphabetically the locations? Thanks!

**Comment by rjcarneiro** [comment]
@marmelo sorry, my bad 🙈 

Updated 👍

**Comment by marmelo** [comment]
No problem, sorry for being picky. Thanks @rjcarneiro!

**Comment by rjcarneiro** [comment]
@marmelo not at all! That's the way should be 😉

**Pull request merged**
