### PR TITLE
Added VOID Software

### PR DESCRIPTION
**Pull request by ClaymorePT**
Added VOID Software

Signed-off-by: Carlos Miguel Ferreira <carlosmf.pt@gmail.com>

### CODE REVIEW

**Comment by vpereira01** [comment]
I think the description should be shorter as it's 37 characters longer than the current biggest description, you probably should aim for 70 characters max.

**Comment by marmelo** [comment]
Hi @ClaymorePT,

I agree with @vpereira01, you description is very long.
Can you please try to shorten it to fit in a single line?

Thanks.

**Comment by ClaymorePT** [comment]
@vpereira01 @marmelo 
Done. It is now under 70 char.

**Comment by marmelo** [comment]
Thanks @ClaymorePT!

**Pull request merged**
