### PR TITLE
Added Moxy

### PR DESCRIPTION
**Pull request by afonsojramos**

### CODE REVIEW

**Comment by marmelo** [comment]
Hi @afonsojramos, can you please shorten your description so that it fits in a single line?
I have just created the missing [CONTRIBUTING.md](https://github.com/marmelo/tech-companies-in-portugal/blob/master/CONTRIBUTING.md), sorry for the delay.

Thanks!

**Comment by afonsojramos** [comment]
Well, on a 1080p screen it fits, but I'll sum it up a bit!

**Comment by afonsojramos** [comment]
Can you check again @marmelo ? Great idea for a repo by the way 😉

**Comment by marmelo** [comment]
Thanks @afonsojramos! It is awesome. ⭐️

**Pull request merged**
