### PR TITLE
Added NCC Group

### PR DESCRIPTION
**Pull request by hzphreak**

### CODE REVIEW

**Comment by marmelo** [comment]
Hi @hzphreak,

Can you please confirm if the Lisbon office has development/tech jobs positions?
I could not find any information about it.

Thanks.

**Comment by hzphreak** [comment]
Hi @marmelo, 

They do have tech jobs, mainly consultancy in Lisbon. I added the careers page https://www.nccgroupplc.com/careers/ to the commit following the guidelines. 

Cheers

**Comment by marmelo** [comment]
@hzphreak  I saw that link, but I did not find any reference to Lisbon jobs -- that is why I asked.

But if you say so, I trust your word. :)

**Review by marmelo — APPROVED** [review]

**Review by afonsojramos — APPROVED** [review]

**Comment by afonsojramos** [comment]
Can't find any Lisbon openings indeed, but if you, @hzphreak, say there is an office there, then it's all good!

**Pull request merged**
