### PR TITLE
Added Critical Techworks

### PR DESCRIPTION
**Pull request by pmiguel**
### Description
This PR adds Critical Techworks to the list.

### Notes:
CTW has a single-page website, with their job listings at the bottom. There is no dedicated careers page.

### CODE REVIEW

**Comment by marmelo** [comment]
Hi @pmiguel, can you please remove the `<br>` in the locations?  
Given that there are only two locations they will fit nicely in a single row.

About the careers link, you may use an anchor to the open roles section: https://www.criticaltechworks.com/#openroll
That said, keeping the same link is also OK. Your call!

Thanks.

**Comment by pmiguel** [comment]
Hey @marmelo!

Added anchor to URL and removed line break as suggested.

**Comment by marmelo** [comment]
Thanks @pmiguel! ⭐️

**Comment by pmiguel** [comment]
@marmelo Welcome! 

I have a few more in my mind. I'll probably submit a few more PRs during the week. Great initiative, btw!

**Pull request merged**
