### PR TITLE
Added Platforme.

### PR DESCRIPTION
**Pull request by gcandal**

### CODE REVIEW

**Comment by marmelo** [comment]
Can you please shorten the description to fit in 1 line to improve readability?
I know there are not rules, I need to create a CONTRIBUTING.md.

Thanks!

**Comment by gcandal** [comment]
Done. In any case, there are already multi-line rows :D

**Comment by marmelo** [comment]
Yes, but not because of the description!

**Comment by gcandal** [comment]
Does that mean that a company with more offices has the right to more publicity? 🤔 j/k, I understand the reason why.

**Comment by marmelo** [comment]
Thanks @gcandal !

**Pull request merged**
