### PR TITLE
Add Salsify

### PR DESCRIPTION
**Pull request by jcmfernandes**
Thanks @marmelo! 🙌

### CODE REVIEW

**Comment by jcmfernandes** [comment]
Sorry about the trailing whitespace, I clearly didn't (still don't honestly) understand why it's there.

**Comment by marmelo** [comment]
Two trailing whitespaces in Markdown produce a line break without a paragraph (spacing).
This is for aesthetical purpose only, sorry. :)

Thanks @jcmfernandes! for the addition! :star:

BTW, very disappointed with you, @donbonifacio. :)

**Comment by jcmfernandes** [comment]
Oh, thanks! It seems like I never had to fine format a large markdown document 😅 .

@donbonifacio shame! 😝

**Comment by donbonifacio** [comment]
🙈

**Comment by ftonato** [comment]
Hey @jcmfernandes,

Do you know whether this company is or not using _Nodejs_?

> https://github.com/ftonato/nodejs-in-portugal

**Comment by jcmfernandes** [comment]
Hey @ftonato,

Thanks for asking. We do not. When it comes to languages/major frameworks, we use Ruby + Rails, and TypeScript + Ember.

**Pull request merged**
