### PR TITLE
ADD SevuPrinting

### PR DESCRIPTION
**Pull request by andre-sevw**

### CODE REVIEW

**Review by afonsojramos — CHANGES_REQUESTED** [review]
Browsing the website, I do not think this company fits the repository.

**Comment by andre-sevw** [comment]
> Browsing the website, I do not think this company fits the repository.

But why not? we also offer direct marketing and personalization printing products such as 360imprimir.

**Comment by afonsojramos** [comment]
Maybe I'm overcomplicating, but by going to [360imprimir's career page](https://www.360imprimir.pt/Home/Carreiras) you can clearly see that they also hire engineers. I do not have the same feedback from SevuPrinting's page.

**Comment by vpereira01** [comment]
Although it's not really explicit the goal of this repository is more/less to list tech companies which a tech person (software developer, DevOps, data science, etc.) might want to join.

In other words, companies already listed have some focus on the technology they use, and develop, and might be interesting for tech people to join them. 

SevuPrinting does not seem to have a tech focus, but only printing focus, and does not seem to have job openings for tech people. Because of this I think SevuPrinting should not be added.

**Pull request closed without merging**
