### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AntWecki**
Damia Group Recruitment

### CODE REVIEW

**Comment by AntWecki** [comment]
Hey @marmelo 
Having some trouble on pushing can you help? I think everything is ok :/

**Comment by AntWecki** [comment]
hey @afonsojramos 
maybe I'm misreading something, what have you noted?

**Comment by afonsojramos** [comment]
@AntWecki I was referring to the fact that consultancy companies are listed with what they do, instead of a proper description. But I am not sure what the standards are right now... @marmelo can you lend a hand?

**Comment by marmelo** [comment]
Hi @afonsojramos, I am not being too picky with the description.
@AntWecki works at Damia, so I trust that he knows how is the company described best.

**Review by marmelo — APPROVED** [review]

**Comment by marmelo** [comment]
Thanks @AntWecki and @afonsojramos.

**Pull request merged**
