### PR TITLE
Add Abyssal company

### PR DESCRIPTION
**Pull request by joaoportela**
Abyssal is a Portuguese company whose main offices are located in Leça da Palmeira (Polo do Mar UPTEC).

I've added a new category because it didn't seem to fit in any of the others. Is that alright?

### CODE REVIEW

**Comment by ftonato** [comment]
Hey @joaoportela,

Do you know whether this company is or not using _Nodejs_?

> https://github.com/ftonato/nodejs-in-portugal

**Comment by joaoportela** [comment]
@ftonato I know that they are not using Nodejs. Thanks for asking.

**Comment by marmelo** [comment]
Hi @joaoportela,

I have some mixed feelings about creating the "Subsea" category.
Isn't it too restrictive? Do you know other portuguese companies in that area?

I know that we already have a category with only one entry (Gaming).
But I really believed that more companies in that area would appear soon.

Do you believe it can fit in an existing category?
If not, can we create a broader one with more chances of having other companies?

What do you think?

Thanks.

**Comment by vpereira01** [comment]
I would propose 3 options:
1. **Sea** instead of sub sea to include over water tech
    * Example https://www.itjobs.pt/empresa/xsealence-sea-technologies
1. **Drone** since relates well to what Abyssal does
    * Example https://www.itjobs.pt/empresa/spin-works
1. **Vehicles** by abstracting "Automotive" into "Vehicles"

**Comment by joaoportela** [comment]
I agree with the change to sea. It would allow for the inclusion of more companies.

As for more companies for sea/subsea I would also suggest [Oceanscan](https://www.oceanscan-mst.com/)

**Comment by marmelo** [comment]
Ok @joaoportela, lets change it to Sea and wait to see if other companies are added.
Feel free to add others or reach out to people working in similar companies. :)

**Comment by marmelo** [comment]
Also, please don't forget to add the new category to the table of contents.

**Comment by marmelo** [comment]
Thanks @joaoportela!

**Pull request merged**
