### PR TITLE
Add TripAdvisor to list of companies

### PR DESCRIPTION
**Pull request by pedrorijo91**
Probably we could think about a new category for tripadvisor, hostelworld, and skyhour in the future

### CODE REVIEW

**Comment by afonsojramos** [comment]
I don't think TripAdvisor belongs on this list, as they do not have IT/Engineering jobs in Portugal...
@marmelo what do you think?

**Comment by pedrorijo91** [comment]
yes they do @afonsojramos  :)

**Comment by marmelo** [comment]
AFAIK TripAdvisor is hiring engineering roles in Lisbon (they need to update their careers page!).
Build is failing but it is not related with this addition.

**Comment by marmelo** [comment]
Thanks @pedrorijo91! :star:

**Comment by ftonato** [comment]
Hey @pedrorijo91,

Do you know whether this company is or not using _Nodejs_?

> https://github.com/ftonato/nodejs-in-portugal

**Comment by pedrorijo91** [comment]
sorry @ftonato but I think your approach is a bit spammy. You are commenting all the PRs of this repo...

**Pull request merged**
