### PR TITLE
Add VAKT Global Ltd.

### PR DESCRIPTION
**Pull request by cmpsoares91**

### CODE REVIEW

**Comment by vpereira01** [comment]
It seems to be that FinTech would be a better category tomorrow.

**Comment by cmpsoares91** [comment]
> It seems to be that FinTech would be a better category tomorrow.

No, because we do not provide a solution for financial markets but for physical commodities markets.

**Comment by marmelo** [comment]
Thanks @cmpsoares91! :star:

**Comment by cmpsoares91** [comment]
Thank you @marmelo

**Pull request merged**
