### PR TITLE
Added Landing.jobs

### PR DESCRIPTION
**Pull request by pdfrod**
Also created category "Marketplaces" since Landing.jobs is a jobs
marketplace and it didn't fit well in the existing categories.

### CODE REVIEW

**Comment by marmelo** [comment]
Hi @pdfrod, sorry for the delay landing this.
The PR is OK, but I am not feeling good in creating a Marketplace category.

LoanDolphin, Trouva and OLX are also marketplaces.
So, does it makes sense for Landing.jobs (job-related) to be in the same category with loan, boutique and trading-related companies?

I would say no.
I believe Landing.jobs should be next to KWAN and Hays.

I am about to create an issue proposing to split the Consultancy category into sub-categories.
One of them would be **Recruiting**, that we could even split more into **Outsourcing** and **Permanent Placement**.

What do you think?

**Comment by marmelo** [comment]
This is the issue #82 to split the **Consultancy** :man_office_worker: category.

**Comment by pdfrod** [comment]
@marmelo To be honest, considering Landing.jobs as Consultancy feels like a big stretch to me - Landing.jobs is nothing like what I'd expect a consultancy firm to be. But I guess, if there's no better category at the moment, it's acceptable.

**Comment by marmelo** [comment]
Hi @pdfrod, I have moved Landing.jobs to the Consultancy category.  
I understand that it is not the most accurate, lets talk later.  
Thanks!

**Comment by pdfrod** [comment]
@marmelo alright, thanks!

**Pull request merged**
