### PR TITLE
Add industry category and Malvern Panalytical

### PR DESCRIPTION
**Pull request by vpereira01**
Enterprise Software category doesn't seem to fit either FARO Technologies or Malvern Panalytical so this PR adds this category for both companies.

Adds Malvern Panalytical company.

### CODE REVIEW

**Review by afonsojramos — APPROVED** [review]
I was trying to find a better name than precision, but can't think of anything.

Other than that, looks good to me!

**Comment by pedrorijo91** [comment]
I also feel precision is not clear to anyone looking at this list for the first time. I'd rather have a company in a not so exact category than having a category that is not clear

Suggestions:

- Maybe move Faro into the Multimedia section, as they work with 3d measurements and etc?
- Create a new section "Industrial" and move malvernpanalytical there?
- Or maybe move faro into this new "Industrial" as well?

just some ideas, let me know your thoughts

**Comment by afonsojramos** [comment]
I actually like your idea of Industrial @pedrorijo91. Maybe Critical Manufacturing would also fit there?

**Review by afonsojramos — APPROVED** [review]
Yeah, I think it looks good now!

**Review by pedrorijo91 — APPROVED** [review]

**Pull request merged**
