### PR TITLE
Add Banco Atlântico Europa

### PR DESCRIPTION
**Pull request by shizpi**

### CODE REVIEW

**Comment by shizpi** [comment]
@marmelo Seems like 3 links are failing in CI
https://www.weareforeteller.com/ is gone, but it's previous domain http://www.growininnovation.com/ is still up, not sure if they are gone or the website is down temporarily

**Comment by vpereira01** [comment]
Please re-check the contributing guide https://github.com/marmelo/tech-companies-in-portugal/blob/master/CONTRIBUTING.md

You missed the point regarding a short description, go for less than 70 chars, and that the company must the placed in order, this one being at the top place.

**Comment by vpereira01** [comment]
Added issue #151 for the issue you raised https://github.com/marmelo/tech-companies-in-portugal/pull/147#issuecomment-565751962

**Comment by shizpi** [comment]
@vpereira01, I corrected the issue for this PR and will do the same regarding order in others

**Comment by marmelo** [comment]
Thanks @shizpi and @vpereira01!

**Pull request merged**
