### PR TITLE
Add Teamlyzer url to companies

### PR DESCRIPTION
**Pull request by shizpi**
Add link for most companies with their teamlyzer url to check the company public feedback.

### CODE REVIEW

**Comment by marmelo** [comment]
Hi @shizpi,

Give me a couple days more to think if this is a good idea.

Thanks!

**Comment by shizpi** [comment]
@marmelo Of course. I believe it's worth having, since it gives an overview about the company when you don't know much about it.

Maybe Glassdoor, also, but I don't think the industry trusts this one that much and Teamlyzer is only for Portuguese companies.

**Comment by afonsojramos** [comment]
Teamlyzer's purpose is very well-intentioned, however, I think it does not have enough data for it to be a worthwhile addition to this repository. 

Glassdoor would probably be a better addition, but even so, I don't know if neither have a place in here.

**Comment by shizpi** [comment]
@afonsojramos What do you mean it does not have enough data? For many of the companies in the current list it has multiple reviews, salaries and even job offers.
https://pt.teamlyzer.com/companies/?order=most_reviewed_job

**Comment by afonsojramos** [comment]
Since I have said this @shizpi I have further explored Teamlyzer's website and found that it has some evident downsides over Glassdoor, e.g., the fact that salaries are very generalized and do not have "all the possible categories". Glassdoor also has Interviews, Benefits and written reviews, which I think are far superior to mere stats.

Let's take an example:

https://www.glassdoor.com/Salary/Blip-Porto-Salaries-EI_IE574750.0,4_IL.5,10_IC3183562.htm
https://pt.teamlyzer.com/companies/blip/salary-reviews

Here, first of all, we can find much more information on Glassdoor's page over Teamlyzer's. Furthermore, Glassdoor has much more position variants since it does not try, by itself, to generalize positions.

In the end, I still agree with @leplastic in #27 where Glassdoor should be the default and Teamlyzer the backup for the small Portuguese companies.

**Comment by shizpi** [comment]
@afonsojramos I agree with the last option to include both. You can also create a PR to add Glassdoor like I did with Teamlyzer.

**Comment by afonsojramos** [comment]
In that case, I approve this merge request and a future merge request with glassdoor will be added.

**Comment by vpereira01** [comment]
I have checked a couple of companies on Teamlyzer and the data is very sparse so it doesn't seem a very good fit to add an URL to all entries. There's a bunch of niche (small/medium) companies here so for them the URL would be kind of useless.

Furthermore I adding a replicated URL all over seems wrong to my coding mind - do not repeat yourself :) 
Company site and career pages seems fine to me because the ease to find their careers page varies  a lot, from good to bad. It's understandable because in many cases their product page is not a good place to place their careers pages' link.

Still I think it's a good idea to remind everyone they can/should ask review sites like Teamlyzer and Glassdoor when checking new opportunities. The tech maybe sexy but the noisy fuzzballs may be a deal breaker.

My compromise solution would be to add a note on top of the list just saying that with somewhat a disclaimer. For example:

---------------------

# Tech Companies in Portugal :portugal:

[Build Status](https://travis-ci.com/marmelo/tech-companies-in-portugal)
[License](https://github.com/marmelo/tech-companies-in-portugal/blob/master/LICENSE)

This is a opinionated list of some technology companies operating in Portugal.  
If you find something wrong or want to add another company please [follow the rules](CONTRIBUTING.md) to contribute with a pull request.

Are you seeking for a job? Click :rocket: to check the company's careers page.

It's also a good idea to check, and give, reviews on [Teamlyzer](https://pt.teamlyzer.com/) and [Glassdoor](https://www.glassdoor.com/Reviews/index.htm) (not sponsored). 

From companies overselling to disgruntled employees reviews, take everything with a grain of salt.

**Comment by afonsojramos** [comment]
To be honest, I think this solution is the best one.

> # Tech Companies in Portugal 🇵🇹
> [Build Status](https://travis-ci.com/marmelo/tech-companies-in-portugal)
> [License](https://github.com/marmelo/tech-companies-in-portugal/blob/master/LICENSE)
> 
> This is a opinionated list of some technology companies operating in Portugal.
> If you find something wrong or want to add another company please [follow the rules](CONTRIBUTING.md) to contribute with a pull request.
> 
> Are you seeking for a job? Click 🚀 to check the company's careers page.
> 
> It's also a good idea to check, and give, reviews on [Teamlyzer](https://pt.teamlyzer.com/) and [Glassdoor](https://www.glassdoor.com/Reviews/index.htm) (not sponsored).
> 
> From companies overselling to disgruntled employees reviews, take everything with a grain of salt.

**Comment by afonsojramos** [comment]
Closed due to the idea of adding a Teamlyzer link being rejected.
A future PR will be made with the suggested changes.

**Pull request closed without merging**
